#!/usr/bin/env bash
# Bash script that displays:
#	The content of the current directory
#	In a list format
#	Where only the part of the name after the first dash is displayed (refer to the example)
for _ in *
do
	echo "$_" | cut -f 2 -d '-'
done
